- name: Epic
  color: 3E4B9E
- name: component/ci
  color: e575b2
  description: "Component: CI Integration"
- name: component/cli
  color: e575b2
  description: "Component: CLI tooling"
- name: component/docs
  color: e575b2
  description: "Component: Documentation"
- name: component/ide
  color: e575b2
  description: "Component: IDE Integration"
- name: component/operator
  color: e575b2
  description: "Component: Operator service"
- name: dependencies
  color: 21ceff
  description: "Dependabot: Pull requests that update a dependency file"
- name: docker
  color: 21ceff
  description: "Dependabot: Pull requests that update Docker code"
- name: external/collaboration
  color: 9596db
  description: "External: outreach/patching/"
- name: go
  color: 21ceff
  description: "Dependabot: Pull requests that update Go code"
- name: internal/infra
  color: e8e540
  description: "Internal: related to project build / setup / release"
- name: internal/test-infra
  color: e8e540
  description: "Internal: related to project testing"
- name: kind/bug
  color: "008672"
  description: "Kind: Not working as expected"
- name: kind/enhancement
  color: "008672"
  description: "Kind: New feature or improvement"
- name: reason/breaking-changes
  color: 8e0b30
  description: "Reason: dependency update with compatibility issues"
- name: skip-changelog
  color: e5950b
  description: "Command: used by changelog generator"
- name: spike
  color: 9d09bf
  description: "Research activity"
- name: upstream
  color: 1fddb7
  description: "Requires changes in the upstream dependency"
