apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sessions.maistra.io
spec:
  group: maistra.io
  names:
    kind: Session
    listKind: SessionList
    plural: sessions
    singular: session
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
