apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sessions.istio.openshift.com
spec:
  group: istio.openshift.com
  names:
    kind: Session
    listKind: SessionList
    plural: sessions
    singular: session
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
