linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 12
  cyclop:
    max-complexity: 12
  dupl:
    threshold: 128
  funlen:
    lines: 128
    statements: 64
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
    packages:
      - github.com/sirupsen/logrus
      - sigs.k8s.io/controller-runtime/pkg/log
      - sigs.k8s.io/controller-runtime/pkg/log/zap
      - sigs.k8s.io/controller-runtime/pkg/runtime/log
  misspell:
    locale: US
    ignore-words:
      - istio
      - k8s
  lll:
    line-length: 180
  goimports:
    local-prefixes: github.com/maistra/istio-workspace
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - commentFormatting # https://github.com/go-critic/go-critic/issues/755
      - hugeParam # seems to be premature optimization based on https://github.com/Maistra/istio-workspace/pull/378#discussion_r392208906
  nestif:
    min-complexity: 8
  unused:
    check-exported: true
  gocognit:
    min-complexity: 16
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - errors.WrapIfWithDetails
      - errors.WithDetails(
      - errors.WrapWithDetails(
      - errors.WrapIf(
      - errors.NewWithDetails(

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - forbidigo
    - gochecknoinits # k8s/istio generated APIs are using init()
    - gochecknoglobals # FIXME https://github.com/Maistra/istio-workspace/issues/479
    - gocognit # FIXME https://github.com/Maistra/istio-workspace/issues/478
    - gofmt # We use goimports and when using them both leads to contradicting errors
    - gofumpt
    - gomnd
    - paralleltest
    - wsl # FIXME https://github.com/Maistra/istio-workspace/issues/481

run:
  deadline: 10m
  skip-dirs:
    - ./pkg/apis
    - ./pkg/assets/generated
    - ./pkg/client/clientset

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: e2e/
      linters:
        - goconst
        - gocyclo
        - godox # tmp
        - golint
        - errcheck
        - dupl
        - gosec
        - revive
        - stylecheck
        - wrapcheck
    - path: test/
      linters:
        - revive
    - path: pkg/log
      linters:
        - depguard
    - path: pkg/openshift/
      linters:
        - dupl
    - path: pkg/k8s/
      linters:
        - dupl
    - path: pkg/apis/
      linters:
        - stylecheck
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - revive
        - wrapcheck
    - path: _suite_test\.go
      linters:
        - revive
        - unused
    - path: pkg/assets/isto-workspace-deploy.go
      linters:
        - wrapcheck
    - path: cmd/test-service/main.pb.go
      linters:
        - wrapcheck
    - path: pkg/client/clientset
      linters:
        - wrapcheck
