linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 12
  dupl:
    threshold: 128
  funlen:
    lines: 128
    statements: 64
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
    packages:
      - github.com/sirupsen/logrus
      - sigs.k8s.io/controller-runtime/pkg/log
      - sigs.k8s.io/controller-runtime/pkg/log/zap
      - sigs.k8s.io/controller-runtime/pkg/runtime/log
  misspell:
    locale: US
    ignore-words:
      - istio
      - k8s
  lll:
    line-length: 180
  goimports:
    local-prefixes: github.com/maistra/istio-workspace
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - commentFormatting # https://github.com/go-critic/go-critic/issues/755
      - hugeParam # seems to be premature optimization based on https://github.com/Maistra/istio-workspace/pull/378#discussion_r392208906
  unused:
    check-exported: true
  gocognit:
    min-complexity: 16

linters:
  enable-all: true
  disable:
    - gochecknoinits # k8s/istio generated APIs are using init()
    - gochecknoglobals # TODO discuss
    - gofmt # We use goimports and when using them both leads to contradicting errors

run:
  deadline: 10m
  skip-dirs:
    - ./pkg/apis
    - ./pkg/assets/generated
    - ./pkg/client/clientset

issues:
  exclude-rules:
    - path: pkg/openshift/
      linters:
        - dupl
    - path: pkg/k8s/
      linters:
        - dupl
    - path: pkg/apis/
      linters:
        - stylecheck
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - unused

service:
  project-path: github.com/maistra/istio-workspace
  golangci-lint-version: 1.19.1 # Locks the version to avoid newly introduces linters
  prepare:
    - make lint-prepare
