image:https://goreportcard.com/badge/github.com/maistra/istio-workspace["Go Report Card", link="https://goreportcard.com/report/github.com/maistra/istio-workspace"]
image:https://circleci.com/gh/Maistra/istio-workspace.svg?style=svg["CircleCI", link="https://circleci.com/gh/Maistra/istio-workspace"]

== Istio Workspace

=== Documentation

More details can be found on our https://istio-workspace-docs.netlify.com/[documentation page]. 

We use amazing https://antora.org/[Antora] project to build it and you should too!

=== Install (in two easy steps)

Get latest `ike` binary through simple download script:

[source,bash]
----
curl -sL http://git.io/get-ike | bash
----

TIP: You can also specify the version and directory before downloading `curl -sL http://git.io/get-ike | bash -s \-- --version=v0.0.1 --dir=/usr/bin`

[source,bash]
----
get - downloads ike binary matching your operating system
 
./get.sh [options]
 
Options:
-h, --help          shows brief help
-v, --version       defines version specific version of the binary to download (defaults to latest)
-d, --dir           target directory to which the binary is downloaded (defaults to random tmp dir in /tmp suffixed with ike-version)
-n, --name          saves binary under specific name (defaults to ike)

----

When logged in to the cluster run the following for a cluster wide operator:

[source,bash]
----
ike install-operator
----

or if you only want to install the operator for a single namespace run:

[source,bash]
----
ike install-operator -l
----

And you are all set!

=== Development Setup

Assuming that you have all the https://golang.org/doc/install[Golang prerequisites] in place, clone the repository first:

[source,bash]
----
$ git clone https://github.com/maistra/istio-workspace $GOPATH/src/github.com/maistra/istio-workspace
----

We rely on following tools:

* https://golang.github.io/dep/[`dep`] for dependency management
* https://github.com/golangci/golangci-lint[`golang-ci`] linter
* https://github.com/onsi/ginkgo[`ginkgo`] for testing
* https://godoc.org/golang.org/x/tools/cmd/goimports[`goimports`] for formatting
* https://github.com/operator-framework/operator-sdk[`operator-sdk`] for code generation

but from now on you are ready to hack - invoking `make` will check if those binaries are available and install if there are some missing.

Run `make help` to see what targets are available, but you will use `make` most often.

NOTE: Have a look how https://github.com/moovweb/gvm[Go Version Manager] can help you simplifying configuration
and management of different versions of Go.

==== Coding style

We follow standard Go coding conventions which we ensure using `goimports` during the build. 

In addition we provide `.editorconfig` file which is supported by https://editorconfig.org/#download[majority of the IDEs].

=== License

This project is licensed under the link:http://www.apache.org/licenses/[Apache License, Version 2.0].