image:https://goreportcard.com/badge/github.com/maistra/istio-workspace["Go Report Card", link="https://goreportcard.com/report/github.com/maistra/istio-workspace"]
image:https://circleci.com/gh/Maistra/istio-workspace.svg?style=svg["CircleCI", link="https://circleci.com/gh/Maistra/istio-workspace"]

== Istio Workspace

=== Documentation

Full documentation preview can be found https://istio-workspace-docs.netlify.com/[here].

==== Setup

Assuming that you have all the https://golang.org/doc/install[Golang prerequisites] in place, clone the repository first:

[source,bash]
----
$ git clone https://github.com/maistra/istio-workspace $GOPATH/src/github.com/maistra/istio-workspace
----

then run `make tools` which will take care of installing all the tools mentioned below:

* https://golang.github.io/dep/[`dep`] for dependency management
* https://github.com/golangci/golangci-lint[`golang-ci`] linter
* https://github.com/onsi/ginkgo[`ginkgo`] for testing
* https://godoc.org/golang.org/x/tools/cmd/goimports[`goimports`] for formatting
* https://github.com/operator-framework/operator-sdk[`operator-sdk`] for code generation

From now on you are ready to hack. Run `make help` to see what targets are available, but you will use
`make build` and `make test` most often.

NOTE: Have a look how https://github.com/moovweb/gvm[Go Version Manager] can help you simplifying configuration
and management of different versions of Go.

==== Coding style

We follow standard Go coding conventions which we ensure using `goimports` during the build. 

In addition we provide `.editorconfig` file which is supported by https://editorconfig.org/#download[majority of the IDEs].

=== License

This project is licensed under the link:http://www.apache.org/licenses/[Apache License, Version 2.0]
.
