kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: NAMESPACE
    description: "Target namespace for which role binding should be defined"
    required: true
    value: istio-workspace-operator
objects:
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: istio-workspace
    subjects:
      - kind: ServiceAccount
        name: istio-workspace
        namespace: ${NAMESPACE}
    roleRef:
      kind: Role
      name: istio-workspace
      apiGroup: rbac.authorization.k8s.io
