// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// An empty request object
type Callee struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Callee) Reset()         { *m = Callee{} }
func (m *Callee) String() string { return proto.CompactTextString(m) }
func (*Callee) ProtoMessage()    {}
func (*Callee) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{0}
}

func (m *Callee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Callee.Unmarshal(m, b)
}
func (m *Callee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Callee.Marshal(b, m, deterministic)
}
func (m *Callee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Callee.Merge(m, src)
}
func (m *Callee) XXX_Size() int {
	return xxx_messageInfo_Callee.Size(m)
}
func (m *Callee) XXX_DiscardUnknown() {
	xxx_messageInfo_Callee.DiscardUnknown(m)
}

var xxx_messageInfo_Callee proto.InternalMessageInfo

// The response message containing information from the called service.
type CallStack struct {
	Caller               string       `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Protocol             string       `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Path                 string       `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Color                string       `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	StartTime            int64        `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int64        `protobuf:"varint,6,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Called               []*CallStack `protobuf:"bytes,7,rep,name=called,proto3" json:"called,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CallStack) Reset()         { *m = CallStack{} }
func (m *CallStack) String() string { return proto.CompactTextString(m) }
func (*CallStack) ProtoMessage()    {}
func (*CallStack) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{1}
}

func (m *CallStack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallStack.Unmarshal(m, b)
}
func (m *CallStack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallStack.Marshal(b, m, deterministic)
}
func (m *CallStack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallStack.Merge(m, src)
}
func (m *CallStack) XXX_Size() int {
	return xxx_messageInfo_CallStack.Size(m)
}
func (m *CallStack) XXX_DiscardUnknown() {
	xxx_messageInfo_CallStack.DiscardUnknown(m)
}

var xxx_messageInfo_CallStack proto.InternalMessageInfo

func (m *CallStack) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func (m *CallStack) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *CallStack) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *CallStack) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *CallStack) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *CallStack) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *CallStack) GetCalled() []*CallStack {
	if m != nil {
		return m.Called
	}
	return nil
}

func init() {
	proto.RegisterType((*Callee)(nil), "Callee")
	proto.RegisterType((*CallStack)(nil), "CallStack")
}

func init() {
	proto.RegisterFile("main.proto", fileDescriptor_7ed94b0a22d11796)
}

var fileDescriptor_7ed94b0a22d11796 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x6e, 0x83, 0x30,
	0x10, 0x45, 0xeb, 0x02, 0x06, 0xa6, 0xbb, 0x51, 0x55, 0x59, 0xa8, 0x95, 0x90, 0x37, 0x65, 0xc5,
	0x82, 0x1e, 0xa1, 0x37, 0x20, 0xb9, 0x80, 0x63, 0x2c, 0x05, 0xc5, 0x60, 0xe4, 0xf8, 0x8a, 0xb9,
	0x57, 0xc4, 0xe0, 0x90, 0xec, 0xfe, 0x7f, 0xdf, 0x96, 0xde, 0x00, 0x4c, 0x6a, 0x9c, 0xdb, 0xc5,
	0xbb, 0xe0, 0x64, 0x01, 0xfc, 0x5f, 0x59, 0x6b, 0x8c, 0xbc, 0x31, 0x28, 0xd7, 0x78, 0x08, 0x4a,
	0x5f, 0xf0, 0x0b, 0xb8, 0x5e, 0xb9, 0x17, 0xac, 0x66, 0x4d, 0xd9, 0xc7, 0x86, 0x15, 0x14, 0xf4,
	0x51, 0x3b, 0x2b, 0xde, 0x69, 0xd9, 0x3b, 0x22, 0xa4, 0x8b, 0x0a, 0x67, 0x91, 0x10, 0xa7, 0x8c,
	0x9f, 0x90, 0x69, 0x67, 0x9d, 0x17, 0x29, 0xc1, 0xad, 0xe0, 0x37, 0x94, 0xd7, 0xa0, 0x7c, 0x38,
	0x8e, 0x93, 0x11, 0x59, 0xcd, 0x9a, 0xa4, 0x7f, 0x02, 0x14, 0x90, 0x9b, 0x79, 0xa0, 0x8d, 0xd3,
	0xf6, 0xa8, 0x28, 0xa3, 0xd5, 0x20, 0xf2, 0x3a, 0x69, 0x3e, 0x3a, 0x68, 0x77, 0xe3, 0x68, 0x38,
	0x74, 0xbf, 0xf1, 0x22, 0x8f, 0x3f, 0x90, 0xae, 0x09, 0xf3, 0x76, 0x3b, 0xb1, 0x7a, 0x79, 0x2e,
	0xdf, 0x4e, 0x9c, 0xc4, 0xff, 0xee, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xec, 0x82, 0x7f, 0x0f,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CallerClient is the client API for Caller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CallerClient interface {
	// Call
	Call(ctx context.Context, in *Callee, opts ...grpc.CallOption) (*CallStack, error)
}

type callerClient struct {
	cc grpc.ClientConnInterface
}

func NewCallerClient(cc grpc.ClientConnInterface) CallerClient {
	return &callerClient{cc}
}

func (c *callerClient) Call(ctx context.Context, in *Callee, opts ...grpc.CallOption) (*CallStack, error) {
	out := new(CallStack)
	err := c.cc.Invoke(ctx, "/Caller/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallerServer is the server API for Caller service.
type CallerServer interface {
	// Call
	Call(context.Context, *Callee) (*CallStack, error)
}

// UnimplementedCallerServer can be embedded to have forward compatible implementations.
type UnimplementedCallerServer struct {
}

func (*UnimplementedCallerServer) Call(ctx context.Context, req *Callee) (*CallStack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}

func RegisterCallerServer(s *grpc.Server, srv CallerServer) {
	s.RegisterService(&_Caller_serviceDesc, srv)
}

func _Caller_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Callee)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallerServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Caller/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallerServer).Call(ctx, req.(*Callee))
	}
	return interceptor(ctx, in, info, handler)
}

var _Caller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Caller",
	HandlerType: (*CallerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Caller_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.proto",
}
