:cmd-changelog: /release
:cmd-rebase: /shipit
:sample-version: v0.0.4
:base-branch: master
:pr-url: https://github.com/bartoszmajsak/istio-workspace/pull/30

= Development Guide

== Release

== Release automation driven by Pull Request

By creating a Pull Request with release notes, we can automate the release process simply by using  two commands in the comments.
You can see actual example {pr-url}[here]. 

=== Changelog generation using `{cmd-changelog}` command

An owner, committer, or a member of our organization can use `{cmd-changelog}` command to trigger changelog generation. `{cmd-changelog}`
command takes a version as an argument that needs to conform https://semver.org/[semantic versioning]. 

For example, commenting `{cmd-changelog} {sample-version}` will trigger changelog generation for the `{sample-version}` version.

Such a comment results in adding commits to created PR which consists of:

* changelog based on all PRs since the last release, which will be appended to release highlights submitted as part of this PR
* "version commit" (e.g. `release: {sample-version}`) which consist of documentation version lock to `{sample-version}` and special `/tag` directive in the message. 
This directive later used to create actual tag when PR is rebased onto `{base-branch}` branch
* commit which reverts documentation version lock back to `latest`

Changelog generation job performs validation and will fail if one of the issues listed below occurs:

* `version` parameter does not conform with https://semver.org/[semantic versioning]
* `version` has been already released
* release notes do not exist (submitting this file is the only thing needed for this {pr-url}[PR])
* any of the PRs created since the last release have no labels and thus cannot be categorized by

In all the cases above PR will have `release / changelog` status set to failure and comment with an appropriate error message will be added
by the bot. You can see that in the {pr-url}[comments of the sample PR].

=== Triggering release process by invoking `{cmd-rebase}`

Once changelog generation succeeds, we can trigger the actual release process. This can be done by commenting with `{cmd-rebase}` command without
any parameters.

This will result in rebasing this PR on top of the target branch if all the required checks have been successful. Once "release commit" appears
on the target branch it will be automatically tagged based on `/tag VERSION` comment in its message. That tag will trigger the
actual release process which consists of:

. build and push tagged docker image to `quay.io` registry
. push cross-compiled binaries and release notes to GitHub
. generation documentation for released version

Diagram below describes the entire process and its artifacts.

.Release automation
image::diagrams/automation-release.svg[Release automation]
// Source: https://drive.google.com/file/d/1m0r9AH3LntqgZ5K_IuF6KVcz5QGF2XhX/view?usp=sharing through draw.io
