apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      name: istio-workspace
  template:
    metadata:
      labels:
        name: istio-workspace
    spec:
      serviceAccountName: istio-workspace
      containers:
        - name: istio-workspace
          image: docker.io/aslakknutsen/istio-workspace:latest
          command:
          - ike
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "istio-workspace"
