apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-workspace
    version: v0.0.3
  name: istio-workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-workspace
      version: v0.0.3
  template:
    metadata:
      labels:
        app: istio-workspace
        version: v0.0.3
      name: istio-workspace
    spec:
      containers:
        - args:
            - serve
          command:
            - ike
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: istio-workspace
          image: quay.io/maistra/istio-workspace:v0.0.3
          imagePullPolicy: Always
          name: istio-workspace
      serviceAccountName: istio-workspace
