// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/maistra/istio-workspace/pkg/client/clientset/versioned/typed/maistra/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeWorkspaceV1alpha1 struct {
	*testing.Fake
}

func (c *FakeWorkspaceV1alpha1) Sessions(namespace string) v1alpha1.SessionInterface {
	return &FakeSessions{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeWorkspaceV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
