version: 1
update_configs:
  - package_manager: "go:dep"
    directory: "/"
    update_schedule: "weekly"
    version_requirement_updates: "increase_versions"
  - package_manager: "docker"
    directory: "/build"
    update_schedule: "weekly"
