== Highlights of v0.0.1 release

Inspired by @bobbytables talk from https://youtu.be/yhvR02UofZE[OSCON 2018] we started hacking on open source tooling realizing the idea of safe development on production.
Now, after long weeks in the making, we are extremely happy to announce the first release of `istio-workspace` project.

With this toolkit, we strive to enable developers to:

____
Develop their microservices locally, using the tools they love!

Connect to other services in the cluster and test their changes!

All of that without interfering with other developers and users!
____

All of it based on https://www.cncf.io/[CNCF] open source projects such as https://istio.io[Istio] and https://telepresence.io[Telepresence].

=== How does it work?

* `ike develop` wraps https://telepresence.io[Telepresence] and let you start local development while being connected to the real services in the cluster
 ** in addition, it will restart the process when any files have been changed (see `--watch` flag)
* `istio-workspace` operator takes care of configuring routes in Istio so that only you can hit your service under development

To learn more head over to the https://istio-workspace-docs.netlify.com/istio-workspace/v0.0.1/index.html[official docs].
