{
 "title": "istio-workspace",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total API Call Failure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(api_http_failures_total)", "legendFormat": "total" }
   ]
  },
  {
   "title": "Total API Calls",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(api_http_total)", "legendFormat": "total" }
   ]
  },
  {
   "title": "Total Reconcile Error",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(controller_runtime_reconcile_total {result=\"error\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Total Reconcile",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (controller_runtime_reconcile_total)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Total Action Failure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(resources_failures_total)" }
   ]
  },
  {
   "title": "Total Actions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum (resources_total)", "legendFormat": "total" }
   ]
  },
  {
   "title": "API Call Failure by Call & Kind",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (client_func, source_kind) (api_http_failures_total)",
     "legendFormat": "{{client_func}} {{source_kind}}"
    }
   ]
  },
  {
   "title": "Action Failure by Action & Kind",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (source_action, source_kind) (resources_failures_total)",
     "legendFormat": "{{source_action}} {{source_kind}}"
    }
   ]
  },
  {
   "title": "API Calls by Kind",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (source_kind) (api_http_total)",
     "legendFormat": "{{source_kind}}"
    }
   ]
  },
  {
   "title": "Actions by action",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(source_action) (resources_total)",
     "legendFormat": "{{source_action}}"
    }
   ]
  },
  {
   "title": "API Calls by Func",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (client_func) (api_http_total)",
     "legendFormat": "{{client_func}}"
    }
   ]
  },
  {
   "title": "Actions by kind",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (source_kind) (resources_total)",
     "legendFormat": "{{source_kind}}"
    }
   ]
  }
 ]
}