name: Go
on:
  pull_request:
    branches:
    - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get tools
      run: | 
        export GOPATH=$HOME/go
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        mkdir -p $GOPATH/src/github.com/`echo $GITHUB_REPOSIOTRY |  awk '{split($0,a,"/"); print a[1]}'`
        ln -s `pwd` $GOPATH/src/github.com/$GITHUB_REPOSIOTR
        cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
        make tools

    - name: Get dependencies
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        cd $(go env GOPATH)/src/github.com/$GITHUB_REPOSITORY
        if [ -f Gopkg.toml ]; then
            make deps
        fi
        
    - name: Build main
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        cd $(go env GOPATH)/src/github.com/$GITHUB_REPOSITORY
        make compile 
