name: Go
on:
  pull_request:
    branches:
    - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get tools
      run: | 
        export PATH=$PATH:$(go env GOPATH)/bin
        make tools

    - name: Get dependencies
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        if [ -f Gopkg.toml ]; then
            make deps
        fi
        
    - name: Build main
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make compile 
