name: Tests Operator Bundle

on:
  pull_request:
    paths:
      - api/**
      - config/**

jobs:
  operatorhub-test:
    runs-on: ubuntu-latest
    env:
      OPP_CONTAINER_OPT: "-i"
    steps:
      - name: Set up Go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.11
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: go/src/github.com/${{ env.REPOSITORY }}
      - name: Set $GOPATH
        run: |
          echo "GOPATH=${{ github.workspace }}/go" >> $GITHUB_ENV
          echo "${{ github.workspace }}/go/bin" >> $GITHUB_PATH
        shell: bash
      - uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Tests bundle
        run: |
          git config --global user.name "GitHub Actions" && git config --global user.email "actions@users.noreply.github.com"
          cd go/src/github.com/${{ env.REPOSITORY }}
          make lint-prepare bundle-test
        shell: bash
      - name: Print test logs on failure
        if: ${{ failure() }}
        run: |
          cat /tmp/test.out
          echo -e "\n--------------------------------------------------------------------------\n"
          cat /tmp/op-test/log.out
        shell: bash
