name: Tests Operator Bundle

on:
  pull_request:
    paths:
      - api/**
      - config/**

jobs:
  operatorhub-test:
    runs-on: ubuntu-latest
    env:
      OPP_CONTAINER_OPT: "-i"
    steps:
      - name: Set up Go env
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: go/src/github.com/${{ env.REPOSITORY }}
      - name: Set $GOPATH
        run: |
          echo "GOPATH=${{ github.workspace }}/go" >> $GITHUB_ENV
          echo "${{ github.workspace }}/go/bin" >> $GITHUB_PATH
        shell: bash
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install required packages
        run: pip install ansible jmespath
      - name: Tests bundle
        run: |
          git config --global user.name "GitHub Actions" && git config --global user.email "actions@users.noreply.github.com"
          cd go/src/github.com/${{ env.REPOSITORY }}
          export IKE_CONTAINER_REPOSITORY=maistra-dev
          podman login -u=${{ secrets.QUAY_ROBOT_NAME }} -p=${{ secrets.QUAY_ROBOT_AUTH }} quay.io
          make container-image container-push bundle
          make lint-prepare bundle-test
        shell: bash
      - name: Print test logs on failure
        if: ${{ failure() }}
        run: |
          cat /tmp/test.out || true
          echo -e "\n--------------------------------------------------------------------------\n"
          cat /tmp/op-test/log.out || true
        shell: bash
