name: circleci-check

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '.circleci/config.yml'

jobs:
  circle-ci-validate:
    name: config validation
    runs-on: ubuntu-20.04
    steps:
      - name: Install CircleCI CLI
        run: |
          curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | bash
        shell: bash
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/github.com/${{ github.repository }}
      - name: Validate CircleCI
        run: |
          cd go/src/github.com/${{ github.repository }}
          circleci config validate
        shell: bash
