name: Validates circleci config
pull_request:
  types: [opened, reopened, synchronize]
  paths:
    - '.circleci/config.yml'

jobs:
  circle-ci-validate:
    name: circle-ci-validate
    runs-on: ubuntu-latest
    steps:
      - name: Install CircleCI CLI
        run: |
          sudo curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | bash
        shell: bash
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/github.com/${{ github.repository }}
      - name: Validate CircleCI
        run: |
          cd go/src/github.com/${{ github.repository }}
          circleci config validate
        shell: bash
